Fix bug of removing item from inventory
medrick-bridge-tech/house-of-the-dead pull request #49
Opened 2023-11-05 09:49 UTC by ArmanAghighi

@URAmiRBin done no scene changes only code had modified

2023-11-05 18:59 UTC, URAmiRBin requested changes, later dismissed

2023-11-05 18:59 UTC, URAmiRBin commented on Assets/Scripts/Inventory/ItemPresenter.cs
> +        [SerializeField] private Sprite emptySlotImage;
since the emptySlotImage for all ItemPresenters is the same, we dont need to use this serializedField, loading from resources would do

2023-11-06 08:25 UTC, RezaKusha approved these changes
well done!

2023-11-06 08:28 UTC, RezaKusha approved these changes

2023-11-06 08:31 UTC, merged