import enemy , enemy animation
medrick-bridge-tech/house-of-the-dead pull request #5
Opened 2023-10-17 13:46 UTC by ArmanAghighi

Add a 3d zombie  model and 8 animation files (idle , run , walk , attack , fall , stand up , death scream ) @URAmiRBin

2023-10-17 14:00 UTC, URAmiRBin requested changes

2023-10-17 14:00 UTC, URAmiRBin commented on Assets/Enemy.meta
The file hierarchy should be like this:

Animations > Enemy > put the enemy animations
Models > Enemy > put the enemy models (fbx)
Textures > Enemy > put the enemy textures
Materials > Enemy > put the enemy materials

2023-10-17 14:00 UTC, URAmiRBin commented on Assets/Enemy.meta
we also can do something like"

Enemy1 > Animations
Enemy1 > Models
Enemy1 > Textures
Enemy1 > Materials

and the Enemy1 is in Enemies folder, and the Enemies is in Characters folder

discuss this with the teammates to choose the best one

2023-10-17 14:00 UTC, URAmiRBin commented on Assets/Resources/BillingMode.json
This file should not be added in this commit, make another commit and remove the wrongly committed files.

2023-10-17 14:00 UTC, URAmiRBin commented on Assets/Scenes/SampleScene.unity
Also this should not be committed

2023-10-17 14:00 UTC, URAmiRBin commented on ProjectSettings/ProjectSettings.asset
Dont commit project settings files as well

2023-10-17 14:00 UTC, URAmiRBin commented on Assets/Enemy/warzombie_f_pedroso.fbx.meta
Go study about fbx importing in Unity, since we are mobile we have to be careful about what we import into the project, so take a look at compression options unity has to offer.

Read these two and apply compression to mesh, animations and textures you have imported.

https://suraj.dev/blog/reducing-build-sizes-in-unity3d
https://www.techarthub.com/an-introduction-to-texture-compression-in-unity/

2023-10-17 14:30 UTC, ArmanAghighi commented
@URAmiRBin did change the location of the file inside the project but I can not find out how to remove the pushed wrong file

2023-10-18 11:31 UTC, ArmanAghighi commented
@URAmiRBin please squash before merge

2023-10-18 11:33 UTC, URAmiRBin approved these changes

2023-10-18 11:33 UTC, merged